# Use new container infrastructure to enable caching
sudo: required
dist: trusty

# language is go
language: go

addons:
  apt:
    packages:
    - libgmp-dev
    - build-essential
    - cmake
    - git
    - libgtk2.0-dev
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libtbb2
    - libtbb-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libjasper-dev
    - libdc1394-22-dev
    - xvfb

before_install:
  # Install OpenCV 3
  - ./travis_build_opencv.sh

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_cache:
  - rm -f $HOME/fresh-cache

script:
  - source ./env.sh
  - go test

# Caching so the next build will be fast as possible.
cache:
  timeout: 1000
  directories:
    - $HOME/usr